// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package passwordresetstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountActivationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type EmailOutbox struct {
	ID             uuid.UUID
	Template       string
	RecipientEmail string
	RecipientName  string
	Subject        string
	HtmlBody       string
	TextBody       string
	Status         string
	Attempts       int32
	MaxAttempts    int32
	NextAttemptAt  time.Time
	ClaimedUntil   *time.Time
	LastError      pgtype.Text
	SentAt         *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type IdempotencyKey struct {
	Scope               string
	IdempotencyKey      string
	RequestHash         []byte
	Status              string
	ResponseStatusCode  pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	CreatedAt           time.Time
	CompletedAt         *time.Time
}

type Item struct {
	ID            int32
	Slug          string
	Name          string
	Category      string
	Tier          pgtype.Int4
	RarityRank    int32
	IsTradeable   bool
	IsAuctionOnly bool
	MaxSupply     pgtype.Int8
	Description   string
	Attributes    []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type LootTable struct {
	ZoneID            string
	ItemID            int32
	MinimumQuantity   int32
	MaximumQuantity   int32
	ChanceBasisPoints int32
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Recipe struct {
	ID             string
	OutputItemID   int32
	OutputQuantity int32
	CraftSeconds   int32
	FeeMicro       int64
	IsEnabled      bool
}

type RecipeInput struct {
	RecipeID string
	ItemID   int32
	Quantity int32
}

type RefreshToken struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	TokenHash        []byte
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	ReplacedBy       *uuid.UUID
	CreatedAt        time.Time
	UserAgent        string
	IpAddress        string
	SessionStartedAt time.Time
}

type ShopSku struct {
	Sku         string
	Name        string
	Description string
	PriceMicro  int64
	SortOrder   int32
	IsEnabled   bool
}

type ShopSkuItem struct {
	Sku      string
	ItemID   int32
	Quantity int32
}

type Upgrade struct {
	ID            string
	FromItemID    int32
	ToItemID      int32
	CraftFeeMicro int64
	BuyPriceMicro pgtype.Int8
	IsEnabled     bool
}

type UpgradeInput struct {
	UpgradeID string
	ItemID    int32
	Quantity  int32
}

type User struct {
	ID               uuid.UUID
	Email            string
	Username         string
	PasswordHash     string
	Status           string
	IsActive         bool
	IsAdmin          bool
	TotpSecretEnc    []byte
	TermsAcceptedAt  time.Time
	ActivatedAt      *time.Time
	LastLoginAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	TotpEnabledAt    *time.Time
	TotpLastUsedStep pgtype.Int8
}

type Zone struct {
	ID                 string
	Name               string
	Description        string
	DurationSeconds    int32
	FuelCost           int32
	MinimumDrillTier   int32
	AllowedShipItemIds []int32
	SortOrder          int32
	IsEnabled          bool
}
