// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package passwordresetstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = $1::timestamptz
WHERE token_hash = $2
  AND used_at IS NULL
  AND expires_at > $1::timestamptz
RETURNING user_id
`

type ConsumePasswordResetTokenParams struct {
	Now       time.Time
	TokenHash []byte
}

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, arg ConsumePasswordResetTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, arg.Now, arg.TokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const expireUnusedPasswordResetTokens = `-- name: ExpireUnusedPasswordResetTokens :exec
UPDATE password_reset_tokens
SET expires_at = $1::timestamptz
WHERE user_id = $2
  AND used_at IS NULL
  AND expires_at > $1::timestamptz
`

type ExpireUnusedPasswordResetTokensParams struct {
	Now    time.Time
	UserID uuid.UUID
}

func (q *Queries) ExpireUnusedPasswordResetTokens(ctx context.Context, arg ExpireUnusedPasswordResetTokensParams) error {
	_, err := q.db.Exec(ctx, expireUnusedPasswordResetTokens, arg.Now, arg.UserID)
	return err
}

const findUsablePasswordResetToken = `-- name: FindUsablePasswordResetToken :one
SELECT tokens.user_id, users.email
FROM password_reset_tokens AS tokens
JOIN users ON users.id = tokens.user_id
WHERE tokens.token_hash = $1
  AND tokens.used_at IS NULL
  AND tokens.expires_at > $2::timestamptz
  AND users.is_active = true
`

type FindUsablePasswordResetTokenParams struct {
	TokenHash []byte
	Now       time.Time
}

type FindUsablePasswordResetTokenRow struct {
	UserID uuid.UUID
	Email  string
}

func (q *Queries) FindUsablePasswordResetToken(ctx context.Context, arg FindUsablePasswordResetTokenParams) (FindUsablePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, findUsablePasswordResetToken, arg.TokenHash, arg.Now)
	var i FindUsablePasswordResetTokenRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}
