// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package passwordresetstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConsumePasswordResetToken(ctx context.Context, arg ConsumePasswordResetTokenParams) (uuid.UUID, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	ExpireUnusedPasswordResetTokens(ctx context.Context, arg ExpireUnusedPasswordResetTokensParams) error
	FindUsablePasswordResetToken(ctx context.Context, arg FindUsablePasswordResetTokenParams) (FindUsablePasswordResetTokenRow, error)
}

var _ Querier = (*Queries)(nil)
