export const chapterPaymentVaultAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "CHAPTER_PAYMENT_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAXIMUM_PRICE_AGE_LIMIT",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SEQUENCER_GRACE_PERIOD",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "UPGRADE_INTERFACE_VERSION",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  { type: "function", name: "acceptOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "eip712Domain",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1", internalType: "bytes1" },
      { name: "name", type: "string", internalType: "string" },
      { name: "version", type: "string", internalType: "string" },
      { name: "chainId", type: "uint256", internalType: "uint256" },
      { name: "verifyingContract", type: "address", internalType: "address" },
      { name: "salt", type: "bytes32", internalType: "bytes32" },
      { name: "extensions", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ethUsdPriceFeed",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract AggregatorV3Interface" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hashPaymentAuthorization",
    inputs: [
      { name: "paymentReference", type: "bytes32", internalType: "bytes32" },
      { name: "payer", type: "address", internalType: "address" },
      { name: "usdCents", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "implementationVersion",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      {
        name: "settings",
        type: "tuple",
        internalType: "struct ChapterPaymentVault.InitializationSettings",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          { name: "treasury", type: "address", internalType: "address" },
          { name: "paymentSigner", type: "address", internalType: "address" },
          { name: "paymentToken", type: "address", internalType: "contract IERC20Metadata" },
          { name: "ethUsdPriceFeed", type: "address", internalType: "contract AggregatorV3Interface" },
          { name: "sequencerUptimeFeed", type: "address", internalType: "contract AggregatorV3Interface" },
          { name: "maximumPriceAge", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isPaymentReferencePaid",
    inputs: [{ name: "paymentReference", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maximumPriceAge",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  { type: "function", name: "pause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "payWithEth",
    inputs: [
      {
        name: "authorization",
        type: "tuple",
        internalType: "struct ChapterPaymentVault.PaymentAuthorization",
        components: [
          { name: "paymentReference", type: "bytes32", internalType: "bytes32" },
          { name: "usdCents", type: "uint256", internalType: "uint256" },
          { name: "deadline", type: "uint256", internalType: "uint256" },
          { name: "signature", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "payWithToken",
    inputs: [
      {
        name: "authorization",
        type: "tuple",
        internalType: "struct ChapterPaymentVault.PaymentAuthorization",
        components: [
          { name: "paymentReference", type: "bytes32", internalType: "bytes32" },
          { name: "usdCents", type: "uint256", internalType: "uint256" },
          { name: "deadline", type: "uint256", internalType: "uint256" },
          { name: "signature", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "paymentSigner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paymentToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proxiableUUID",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quoteTokenUnits",
    inputs: [{ name: "usdCents", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quoteWei",
    inputs: [{ name: "usdCents", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "view" },
  {
    type: "function",
    name: "sequencerUptimeFeed",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract AggregatorV3Interface" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setEthUsdPriceFeed",
    inputs: [{ name: "newPriceFeed", type: "address", internalType: "contract AggregatorV3Interface" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaximumPriceAge",
    inputs: [{ name: "newMaximumPriceAge", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPaymentSigner",
    inputs: [{ name: "newPaymentSigner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSequencerUptimeFeed",
    inputs: [{ name: "newUptimeFeed", type: "address", internalType: "contract AggregatorV3Interface" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTreasury",
    inputs: [{ name: "newTreasury", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  { type: "function", name: "unpause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "upgradeToAndCall",
    inputs: [
      { name: "newImplementation", type: "address", internalType: "address" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "withdrawEth",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawToken",
    inputs: [
      { name: "token", type: "address", internalType: "contract IERC20" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "event", name: "EIP712DomainChanged", inputs: [], anonymous: false },
  {
    type: "event",
    name: "EthUsdPriceFeedChanged",
    inputs: [
      { name: "previousPriceFeed", type: "address", indexed: true, internalType: "address" },
      { name: "newPriceFeed", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EthWithdrawn",
    inputs: [
      { name: "treasury", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [{ name: "version", type: "uint64", indexed: false, internalType: "uint64" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "MaximumPriceAgeChanged",
    inputs: [
      { name: "previousMaximumPriceAge", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newMaximumPriceAge", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    inputs: [
      { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
      { name: "newOwner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
      { name: "newOwner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentReceived",
    inputs: [
      { name: "paymentReference", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "payer", type: "address", indexed: true, internalType: "address" },
      { name: "asset", type: "address", indexed: true, internalType: "address" },
      { name: "amountPaid", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "usdCents", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentSignerChanged",
    inputs: [
      { name: "previousPaymentSigner", type: "address", indexed: true, internalType: "address" },
      { name: "newPaymentSigner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SequencerUptimeFeedChanged",
    inputs: [
      { name: "previousUptimeFeed", type: "address", indexed: true, internalType: "address" },
      { name: "newUptimeFeed", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokenWithdrawn",
    inputs: [
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "treasury", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TreasuryChanged",
    inputs: [
      { name: "previousTreasury", type: "address", indexed: true, internalType: "address" },
      { name: "newTreasury", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "Upgraded",
    inputs: [{ name: "implementation", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  { type: "error", name: "AddressEmptyCode", inputs: [{ name: "target", type: "address", internalType: "address" }] },
  {
    type: "error",
    name: "ERC1967InvalidImplementation",
    inputs: [{ name: "implementation", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ERC1967NonPayable", inputs: [] },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "FailedCall", inputs: [] },
  {
    type: "error",
    name: "InsufficientBalance",
    inputs: [
      { name: "balance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InsufficientEthSent",
    inputs: [
      { name: "requiredWei", type: "uint256", internalType: "uint256" },
      { name: "sentWei", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "InvalidEthUsdPrice", inputs: [{ name: "price", type: "int256", internalType: "int256" }] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  {
    type: "error",
    name: "InvalidMaximumPriceAge",
    inputs: [{ name: "maximumPriceAge", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "InvalidPaymentAuthorization", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address", internalType: "address" }] },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "OwnershipCannotBeRenounced", inputs: [] },
  {
    type: "error",
    name: "PaymentAlreadyMade",
    inputs: [{ name: "paymentReference", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "error",
    name: "PaymentAuthorizationExpired",
    inputs: [{ name: "deadline", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeCastOverflowedIntToUint",
    inputs: [{ name: "value", type: "int256", internalType: "int256" }],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "SequencerDown", inputs: [] },
  {
    type: "error",
    name: "SequencerGracePeriodNotOver",
    inputs: [{ name: "sequencerStartedAt", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "StaleEthUsdPrice",
    inputs: [{ name: "updatedAt", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "UUPSUnauthorizedCallContext", inputs: [] },
  {
    type: "error",
    name: "UUPSUnsupportedProxiableUUID",
    inputs: [{ name: "slot", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "error",
    name: "UnsupportedTokenDecimals",
    inputs: [{ name: "decimals", type: "uint8", internalType: "uint8" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroPaymentAmount", inputs: [] },
] as const;
