// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package paymentsstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimPendingPayment = `-- name: ClaimPendingPayment :one
UPDATE payments
SET status = 'SUCCEEDED', credited_micro = $1, succeeded_at = $2, updated_at = $2
WHERE id = $3 AND status = 'PENDING'
RETURNING id, user_id, purpose, method, status, amount_micro, sku, credited_micro, purpose_status, purpose_failure_code, provider_session_id, checkout_url, expires_at, succeeded_at, created_at, updated_at, quantity
`

type ClaimPendingPaymentParams struct {
	CreditedMicro *int64
	SucceededAt   *time.Time
	ID            uuid.UUID
}

func (q *Queries) ClaimPendingPayment(ctx context.Context, arg ClaimPendingPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, claimPendingPayment, arg.CreditedMicro, arg.SucceededAt, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Method,
		&i.Status,
		&i.AmountMicro,
		&i.Sku,
		&i.CreditedMicro,
		&i.PurposeStatus,
		&i.PurposeFailureCode,
		&i.ProviderSessionID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
	)
	return i, err
}

const expirePendingPayments = `-- name: ExpirePendingPayments :many
UPDATE payments
SET status = 'EXPIRED', updated_at = $1
WHERE status = 'PENDING' AND expires_at <= $1
RETURNING id
`

func (q *Queries) ExpirePendingPayments(ctx context.Context, now time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, expirePendingPayments, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayment = `-- name: GetPayment :one
SELECT id, user_id, purpose, method, status, amount_micro, sku, credited_micro, purpose_status, purpose_failure_code, provider_session_id, checkout_url, expires_at, succeeded_at, created_at, updated_at, quantity FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Method,
		&i.Status,
		&i.AmountMicro,
		&i.Sku,
		&i.CreditedMicro,
		&i.PurposeStatus,
		&i.PurposeFailureCode,
		&i.ProviderSessionID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
	)
	return i, err
}

const getPaymentForUser = `-- name: GetPaymentForUser :one
SELECT id, user_id, purpose, method, status, amount_micro, sku, credited_micro, purpose_status, purpose_failure_code, provider_session_id, checkout_url, expires_at, succeeded_at, created_at, updated_at, quantity FROM payments WHERE id = $1 AND user_id = $2
`

type GetPaymentForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPaymentForUser(ctx context.Context, arg GetPaymentForUserParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentForUser, arg.ID, arg.UserID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Method,
		&i.Status,
		&i.AmountMicro,
		&i.Sku,
		&i.CreditedMicro,
		&i.PurposeStatus,
		&i.PurposeFailureCode,
		&i.ProviderSessionID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
	)
	return i, err
}

const insertExternalEvent = `-- name: InsertExternalEvent :one
INSERT INTO external_events (id, provider, event_type, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
RETURNING id
`

type InsertExternalEventParams struct {
	ID        string
	Provider  string
	EventType string
	Payload   []byte
}

func (q *Queries) InsertExternalEvent(ctx context.Context, arg InsertExternalEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertExternalEvent,
		arg.ID,
		arg.Provider,
		arg.EventType,
		arg.Payload,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (id, user_id, purpose, method, amount_micro, sku, quantity, provider_session_id, checkout_url, expires_at, created_at, updated_at)
VALUES (
    $1, $2, $3, $4, $5, $6::text, $7,
    $8::text, $9::text, $10, $11, $11
)
RETURNING id, user_id, purpose, method, status, amount_micro, sku, credited_micro, purpose_status, purpose_failure_code, provider_session_id, checkout_url, expires_at, succeeded_at, created_at, updated_at, quantity
`

type InsertPaymentParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Purpose           string
	Method            string
	AmountMicro       int64
	Sku               *string
	Quantity          int32
	ProviderSessionID *string
	CheckoutUrl       *string
	ExpiresAt         time.Time
	CreatedAt         time.Time
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.Method,
		arg.AmountMicro,
		arg.Sku,
		arg.Quantity,
		arg.ProviderSessionID,
		arg.CheckoutUrl,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Method,
		&i.Status,
		&i.AmountMicro,
		&i.Sku,
		&i.CreditedMicro,
		&i.PurposeStatus,
		&i.PurposeFailureCode,
		&i.ProviderSessionID,
		&i.CheckoutUrl,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
	)
	return i, err
}

const listPaymentsForUser = `-- name: ListPaymentsForUser :many
SELECT id, user_id, purpose, method, status, amount_micro, sku, credited_micro, purpose_status, purpose_failure_code, provider_session_id, checkout_url, expires_at, succeeded_at, created_at, updated_at, quantity FROM payments
WHERE user_id = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3
`

type ListPaymentsForUserParams struct {
	UserID   uuid.UUID
	BeforeID *uuid.UUID
	RowLimit int32
}

func (q *Queries) ListPaymentsForUser(ctx context.Context, arg ListPaymentsForUserParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForUser, arg.UserID, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.Method,
			&i.Status,
			&i.AmountMicro,
			&i.Sku,
			&i.CreditedMicro,
			&i.PurposeStatus,
			&i.PurposeFailureCode,
			&i.ProviderSessionID,
			&i.CheckoutUrl,
			&i.ExpiresAt,
			&i.SucceededAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExternalEventProcessed = `-- name: MarkExternalEventProcessed :exec
UPDATE external_events SET processed_at = now() WHERE id = $1
`

func (q *Queries) MarkExternalEventProcessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markExternalEventProcessed, id)
	return err
}

const recordPurposeOutcome = `-- name: RecordPurposeOutcome :exec
UPDATE payments
SET purpose_status = $1, purpose_failure_code = $2::text, updated_at = now()
WHERE id = $3
`

type RecordPurposeOutcomeParams struct {
	PurposeStatus      string
	PurposeFailureCode *string
	ID                 uuid.UUID
}

func (q *Queries) RecordPurposeOutcome(ctx context.Context, arg RecordPurposeOutcomeParams) error {
	_, err := q.db.Exec(ctx, recordPurposeOutcome, arg.PurposeStatus, arg.PurposeFailureCode, arg.ID)
	return err
}

const sumRecentCardTopups = `-- name: SumRecentCardTopups :one
SELECT COALESCE(SUM(amount_micro), 0)::bigint AS total_micro
FROM payments
WHERE user_id = $1
  AND purpose = 'TOPUP'
  AND method = 'card'
  AND created_at >= $2
  AND (status IN ('SUCCEEDED', 'REFUNDED', 'DISPUTED') OR (status = 'PENDING' AND expires_at > $3))
`

type SumRecentCardTopupsParams struct {
	UserID uuid.UUID
	Since  time.Time
	Now    time.Time
}

func (q *Queries) SumRecentCardTopups(ctx context.Context, arg SumRecentCardTopupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumRecentCardTopups, arg.UserID, arg.Since, arg.Now)
	var total_micro int64
	err := row.Scan(&total_micro)
	return total_micro, err
}
