// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package paymentsstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimPendingPayment(ctx context.Context, arg ClaimPendingPaymentParams) (Payment, error)
	ExpirePendingPayment(ctx context.Context, arg ExpirePendingPaymentParams) (uuid.UUID, error)
	ExpirePendingPayments(ctx context.Context, now time.Time) ([]uuid.UUID, error)
	FailPendingPayment(ctx context.Context, arg FailPendingPaymentParams) (Payment, error)
	GetPayment(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentForUser(ctx context.Context, arg GetPaymentForUserParams) (Payment, error)
	InsertExternalEvent(ctx context.Context, arg InsertExternalEventParams) (string, error)
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error)
	ListPaymentsForUser(ctx context.Context, arg ListPaymentsForUserParams) ([]Payment, error)
	MarkExternalEventProcessed(ctx context.Context, id string) error
	RecordPurposeOutcome(ctx context.Context, arg RecordPurposeOutcomeParams) error
	SumRecentCardTopups(ctx context.Context, arg SumRecentCardTopupsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
