// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package twofactorstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimTotpStep(ctx context.Context, arg ClaimTotpStepParams) (int64, error)
	DisableTotp(ctx context.Context, arg DisableTotpParams) error
	EnableTotp(ctx context.Context, arg EnableTotpParams) (int64, error)
	FindTwoFactorState(ctx context.Context, id uuid.UUID) (FindTwoFactorStateRow, error)
	SetPendingTotpSecret(ctx context.Context, arg SetPendingTotpSecretParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
