// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: two_factor.sql

package twofactorstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimTotpStep = `-- name: ClaimTotpStep :execrows
UPDATE users
SET totp_last_used_step = $1::bigint
WHERE id = $2 AND (totp_last_used_step IS NULL OR totp_last_used_step < $1::bigint)
`

type ClaimTotpStepParams struct {
	Step int64
	ID   uuid.UUID
}

func (q *Queries) ClaimTotpStep(ctx context.Context, arg ClaimTotpStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimTotpStep, arg.Step, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableTotp = `-- name: DisableTotp :exec
UPDATE users
SET totp_secret_enc = NULL, totp_enabled_at = NULL, totp_last_used_step = NULL, updated_at = $1::timestamptz
WHERE id = $2
`

type DisableTotpParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) DisableTotp(ctx context.Context, arg DisableTotpParams) error {
	_, err := q.db.Exec(ctx, disableTotp, arg.Now, arg.ID)
	return err
}

const enableTotp = `-- name: EnableTotp :execrows
UPDATE users
SET totp_enabled_at = $1::timestamptz, updated_at = $1::timestamptz
WHERE id = $2 AND totp_enabled_at IS NULL AND totp_secret_enc IS NOT NULL
`

type EnableTotpParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) EnableTotp(ctx context.Context, arg EnableTotpParams) (int64, error) {
	result, err := q.db.Exec(ctx, enableTotp, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTwoFactorState = `-- name: FindTwoFactorState :one
SELECT email, username, totp_secret_enc, totp_enabled_at
FROM users
WHERE id = $1
`

type FindTwoFactorStateRow struct {
	Email         string
	Username      string
	TotpSecretEnc []byte
	TotpEnabledAt *time.Time
}

func (q *Queries) FindTwoFactorState(ctx context.Context, id uuid.UUID) (FindTwoFactorStateRow, error) {
	row := q.db.QueryRow(ctx, findTwoFactorState, id)
	var i FindTwoFactorStateRow
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.TotpSecretEnc,
		&i.TotpEnabledAt,
	)
	return i, err
}

const setPendingTotpSecret = `-- name: SetPendingTotpSecret :execrows
UPDATE users
SET totp_secret_enc = $1, updated_at = $2::timestamptz
WHERE id = $3 AND totp_enabled_at IS NULL
`

type SetPendingTotpSecretParams struct {
	TotpSecretEnc []byte
	Now           time.Time
	ID            uuid.UUID
}

func (q *Queries) SetPendingTotpSecret(ctx context.Context, arg SetPendingTotpSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPendingTotpSecret, arg.TotpSecretEnc, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
