// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sessionstore

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	FindRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (FindRefreshTokenForUpdateRow, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
