// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_activation_tokens.sql

package activationstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createActivationToken = `-- name: CreateActivationToken :exec
INSERT INTO account_activation_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateActivationTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateActivationToken(ctx context.Context, arg CreateActivationTokenParams) error {
	_, err := q.db.Exec(ctx, createActivationToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}
