// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package activationstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountActivationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type EmailOutbox struct {
	ID             uuid.UUID
	Template       string
	RecipientEmail string
	RecipientName  string
	Subject        string
	HtmlBody       string
	TextBody       string
	Status         string
	Attempts       int32
	MaxAttempts    int32
	NextAttemptAt  time.Time
	ClaimedUntil   *time.Time
	LastError      pgtype.Text
	SentAt         *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type IdempotencyKey struct {
	Scope               string
	IdempotencyKey      string
	RequestHash         []byte
	Status              string
	ResponseStatusCode  pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	CreatedAt           time.Time
	CompletedAt         *time.Time
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type RefreshToken struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	TokenHash        []byte
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	ReplacedBy       *uuid.UUID
	CreatedAt        time.Time
	UserAgent        string
	IpAddress        string
	SessionStartedAt time.Time
}

type User struct {
	ID               uuid.UUID
	Email            string
	Username         string
	PasswordHash     string
	Status           string
	IsActive         bool
	IsAdmin          bool
	TotpSecretEnc    []byte
	TermsAcceptedAt  time.Time
	ActivatedAt      *time.Time
	LastLoginAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	TotpEnabledAt    *time.Time
	TotpLastUsedStep pgtype.Int8
}
