// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package activationstore

import (
	"context"
)

type Querier interface {
	CreateActivationToken(ctx context.Context, arg CreateActivationTokenParams) error
}

var _ Querier = (*Queries)(nil)
