// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package activationstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConsumeActivationToken(ctx context.Context, arg ConsumeActivationTokenParams) (uuid.UUID, error)
	CreateActivationToken(ctx context.Context, arg CreateActivationTokenParams) error
	ExpireUnusedActivationTokens(ctx context.Context, arg ExpireUnusedActivationTokensParams) error
	FindActivationTokenWithUser(ctx context.Context, tokenHash []byte) (FindActivationTokenWithUserRow, error)
}

var _ Querier = (*Queries)(nil)
