// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package missionsstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const abortMission = `-- name: AbortMission :one
UPDATE missions
SET status = 'ABORTED', aborted_at = $1
WHERE id = $2 AND user_id = $3 AND status = 'RUNNING' AND ends_at > $1
RETURNING id, user_id, zone_id, ship_item_id, drill_item_id, status, fuel_spent, ship_hold_id, drill_hold_id, zone_snapshot, loot, started_at, ends_at, resolved_at, collected_at, aborted_at
`

type AbortMissionParams struct {
	AbortedAt *time.Time
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) AbortMission(ctx context.Context, arg AbortMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, abortMission, arg.AbortedAt, arg.ID, arg.UserID)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneID,
		&i.ShipItemID,
		&i.DrillItemID,
		&i.Status,
		&i.FuelSpent,
		&i.ShipHoldID,
		&i.DrillHoldID,
		&i.ZoneSnapshot,
		&i.Loot,
		&i.StartedAt,
		&i.EndsAt,
		&i.ResolvedAt,
		&i.CollectedAt,
		&i.AbortedAt,
	)
	return i, err
}

const collectMission = `-- name: CollectMission :one
UPDATE missions
SET status = 'COLLECTED', collected_at = $1
WHERE id = $2 AND user_id = $3 AND status = 'COMPLETED'
RETURNING id, user_id, zone_id, ship_item_id, drill_item_id, status, fuel_spent, ship_hold_id, drill_hold_id, zone_snapshot, loot, started_at, ends_at, resolved_at, collected_at, aborted_at
`

type CollectMissionParams struct {
	CollectedAt *time.Time
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) CollectMission(ctx context.Context, arg CollectMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, collectMission, arg.CollectedAt, arg.ID, arg.UserID)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneID,
		&i.ShipItemID,
		&i.DrillItemID,
		&i.Status,
		&i.FuelSpent,
		&i.ShipHoldID,
		&i.DrillHoldID,
		&i.ZoneSnapshot,
		&i.Loot,
		&i.StartedAt,
		&i.EndsAt,
		&i.ResolvedAt,
		&i.CollectedAt,
		&i.AbortedAt,
	)
	return i, err
}

const completeMission = `-- name: CompleteMission :one
UPDATE missions
SET status = 'COMPLETED', loot = $1, resolved_at = $2
WHERE id = $3 AND status = 'RUNNING'
RETURNING id
`

type CompleteMissionParams struct {
	Loot       []byte
	ResolvedAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) CompleteMission(ctx context.Context, arg CompleteMissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, completeMission, arg.Loot, arg.ResolvedAt, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countActiveMissions = `-- name: CountActiveMissions :one
SELECT count(*)::integer FROM missions WHERE user_id = $1 AND status IN ('RUNNING', 'COMPLETED')
`

func (q *Queries) CountActiveMissions(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveMissions, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getMissionForUser = `-- name: GetMissionForUser :one
SELECT id, user_id, zone_id, ship_item_id, drill_item_id, status, fuel_spent, ship_hold_id, drill_hold_id, zone_snapshot, loot, started_at, ends_at, resolved_at, collected_at, aborted_at FROM missions WHERE id = $1 AND user_id = $2
`

type GetMissionForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMissionForUser(ctx context.Context, arg GetMissionForUserParams) (Mission, error) {
	row := q.db.QueryRow(ctx, getMissionForUser, arg.ID, arg.UserID)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneID,
		&i.ShipItemID,
		&i.DrillItemID,
		&i.Status,
		&i.FuelSpent,
		&i.ShipHoldID,
		&i.DrillHoldID,
		&i.ZoneSnapshot,
		&i.Loot,
		&i.StartedAt,
		&i.EndsAt,
		&i.ResolvedAt,
		&i.CollectedAt,
		&i.AbortedAt,
	)
	return i, err
}

const insertMission = `-- name: InsertMission :one
INSERT INTO missions (id, user_id, zone_id, ship_item_id, drill_item_id, fuel_spent, ship_hold_id, drill_hold_id, zone_snapshot, started_at, ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, zone_id, ship_item_id, drill_item_id, status, fuel_spent, ship_hold_id, drill_hold_id, zone_snapshot, loot, started_at, ends_at, resolved_at, collected_at, aborted_at
`

type InsertMissionParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ZoneID       string
	ShipItemID   int32
	DrillItemID  int32
	FuelSpent    int32
	ShipHoldID   uuid.UUID
	DrillHoldID  uuid.UUID
	ZoneSnapshot []byte
	StartedAt    time.Time
	EndsAt       time.Time
}

func (q *Queries) InsertMission(ctx context.Context, arg InsertMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, insertMission,
		arg.ID,
		arg.UserID,
		arg.ZoneID,
		arg.ShipItemID,
		arg.DrillItemID,
		arg.FuelSpent,
		arg.ShipHoldID,
		arg.DrillHoldID,
		arg.ZoneSnapshot,
		arg.StartedAt,
		arg.EndsAt,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ZoneID,
		&i.ShipItemID,
		&i.DrillItemID,
		&i.Status,
		&i.FuelSpent,
		&i.ShipHoldID,
		&i.DrillHoldID,
		&i.ZoneSnapshot,
		&i.Loot,
		&i.StartedAt,
		&i.EndsAt,
		&i.ResolvedAt,
		&i.CollectedAt,
		&i.AbortedAt,
	)
	return i, err
}

const listDueMissions = `-- name: ListDueMissions :many
SELECT id, user_id, zone_id, ship_item_id, drill_item_id, status, fuel_spent, ship_hold_id, drill_hold_id, zone_snapshot, loot, started_at, ends_at, resolved_at, collected_at, aborted_at FROM missions
WHERE status = 'RUNNING' AND ends_at <= $1
ORDER BY ends_at
LIMIT $2
`

type ListDueMissionsParams struct {
	Now      time.Time
	RowLimit int32
}

func (q *Queries) ListDueMissions(ctx context.Context, arg ListDueMissionsParams) ([]Mission, error) {
	rows, err := q.db.Query(ctx, listDueMissions, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mission
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ZoneID,
			&i.ShipItemID,
			&i.DrillItemID,
			&i.Status,
			&i.FuelSpent,
			&i.ShipHoldID,
			&i.DrillHoldID,
			&i.ZoneSnapshot,
			&i.Loot,
			&i.StartedAt,
			&i.EndsAt,
			&i.ResolvedAt,
			&i.CollectedAt,
			&i.AbortedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionsForUser = `-- name: ListMissionsForUser :many
SELECT id, user_id, zone_id, ship_item_id, drill_item_id, status, fuel_spent, ship_hold_id, drill_hold_id, zone_snapshot, loot, started_at, ends_at, resolved_at, collected_at, aborted_at FROM missions
WHERE user_id = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
  AND (cardinality($3::text[]) = 0 OR status = ANY($3::text[]))
ORDER BY id DESC
LIMIT $4
`

type ListMissionsForUserParams struct {
	UserID   uuid.UUID
	BeforeID *uuid.UUID
	Statuses []string
	RowLimit int32
}

func (q *Queries) ListMissionsForUser(ctx context.Context, arg ListMissionsForUserParams) ([]Mission, error) {
	rows, err := q.db.Query(ctx, listMissionsForUser,
		arg.UserID,
		arg.BeforeID,
		arg.Statuses,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mission
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ZoneID,
			&i.ShipItemID,
			&i.DrillItemID,
			&i.Status,
			&i.FuelSpent,
			&i.ShipHoldID,
			&i.DrillHoldID,
			&i.ZoneSnapshot,
			&i.Loot,
			&i.StartedAt,
			&i.EndsAt,
			&i.ResolvedAt,
			&i.CollectedAt,
			&i.AbortedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlayerMissions = `-- name: LockPlayerMissions :exec
SELECT pg_advisory_xact_lock(hashtextextended('nebula-missions:' || $1::text, 0))
`

func (q *Queries) LockPlayerMissions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, lockPlayerMissions, userID)
	return err
}
