// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package missionsstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AbortMission(ctx context.Context, arg AbortMissionParams) (Mission, error)
	CollectMission(ctx context.Context, arg CollectMissionParams) (Mission, error)
	CompleteMission(ctx context.Context, arg CompleteMissionParams) (uuid.UUID, error)
	CountActiveMissions(ctx context.Context, userID uuid.UUID) (int32, error)
	GetMissionForUser(ctx context.Context, arg GetMissionForUserParams) (Mission, error)
	InsertMission(ctx context.Context, arg InsertMissionParams) (Mission, error)
	ListDueMissions(ctx context.Context, arg ListDueMissionsParams) ([]Mission, error)
	ListMissionsForUser(ctx context.Context, arg ListMissionsForUserParams) ([]Mission, error)
	LockPlayerMissions(ctx context.Context, userID string) error
}

var _ Querier = (*Queries)(nil)
