// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package maintenancestore

import (
	"context"
	"time"
)

const deleteExpiredActivationTokens = `-- name: DeleteExpiredActivationTokens :execrows
DELETE FROM account_activation_tokens
WHERE expires_at < $1::timestamptz
`

func (q *Queries) DeleteExpiredActivationTokens(ctx context.Context, expiredBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredActivationTokens, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows
DELETE FROM password_reset_tokens
WHERE expires_at < $1::timestamptz
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context, expiredBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNeverActivatedUsers = `-- name: DeleteNeverActivatedUsers :execrows
DELETE FROM users
WHERE is_active = false AND created_at < $1::timestamptz
`

func (q *Queries) DeleteNeverActivatedUsers(ctx context.Context, createdBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNeverActivatedUsers, createdBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldIdempotencyKeys = `-- name: DeleteOldIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE created_at < $1::timestamptz
`

func (q *Queries) DeleteOldIdempotencyKeys(ctx context.Context, createdBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldIdempotencyKeys, createdBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldSentEmails = `-- name: DeleteOldSentEmails :execrows
DELETE FROM email_outbox
WHERE status = 'sent' AND sent_at < $1::timestamptz
`

func (q *Queries) DeleteOldSentEmails(ctx context.Context, sentBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldSentEmails, sentBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleRefreshTokens = `-- name: DeleteStaleRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at < $1::timestamptz
   OR (revoked_at IS NOT NULL AND revoked_at < $1::timestamptz)
`

func (q *Queries) DeleteStaleRefreshTokens(ctx context.Context, staleBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleRefreshTokens, staleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
