// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package maintenancestore

import (
	"context"
	"time"
)

type Querier interface {
	DeleteExpiredActivationTokens(ctx context.Context, expiredBefore time.Time) (int64, error)
	DeleteExpiredPasswordResetTokens(ctx context.Context, expiredBefore time.Time) (int64, error)
	DeleteNeverActivatedUsers(ctx context.Context, createdBefore time.Time) (int64, error)
	DeleteOldIdempotencyKeys(ctx context.Context, createdBefore time.Time) (int64, error)
	DeleteOldSentEmails(ctx context.Context, sentBefore time.Time) (int64, error)
	DeleteStaleRefreshTokens(ctx context.Context, staleBefore time.Time) (int64, error)
}

var _ Querier = (*Queries)(nil)
