// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountActivationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type IdempotencyKey struct {
	Scope               string
	IdempotencyKey      string
	RequestHash         []byte
	Status              string
	ResponseStatusCode  pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	CreatedAt           time.Time
	CompletedAt         *time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	Username        string
	PasswordHash    string
	Status          string
	IsActive        bool
	IsAdmin         bool
	TotpSecretEnc   []byte
	TermsAcceptedAt time.Time
	ActivatedAt     *time.Time
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
