// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateUser(ctx context.Context, arg ActivateUserParams) (ActivateUserRow, error)
	CheckIdentifiersTaken(ctx context.Context, arg CheckIdentifiersTakenParams) (CheckIdentifiersTakenRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error)
	FindUserCredentialsByEmail(ctx context.Context, email string) (FindUserCredentialsByEmailRow, error)
	RecordLogin(ctx context.Context, arg RecordLoginParams) error
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (string, error)
}

var _ Querier = (*Queries)(nil)
