// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersstore

import (
	"context"
)

type Querier interface {
	CheckIdentifiersTaken(ctx context.Context, arg CheckIdentifiersTakenParams) (CheckIdentifiersTakenRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
}

var _ Querier = (*Queries)(nil)
