// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package usersstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkIdentifiersTaken = `-- name: CheckIdentifiersTaken :one
SELECT
    EXISTS (SELECT 1 FROM users WHERE lower(users.email) = lower($1::text)) AS is_email_taken,
    EXISTS (SELECT 1 FROM users WHERE lower(users.username) = lower($2::text)) AS is_username_taken
`

type CheckIdentifiersTakenParams struct {
	Email    string
	Username string
}

type CheckIdentifiersTakenRow struct {
	IsEmailTaken    bool
	IsUsernameTaken bool
}

func (q *Queries) CheckIdentifiersTaken(ctx context.Context, arg CheckIdentifiersTakenParams) (CheckIdentifiersTakenRow, error) {
	row := q.db.QueryRow(ctx, checkIdentifiersTaken, arg.Email, arg.Username)
	var i CheckIdentifiersTakenRow
	err := row.Scan(&i.IsEmailTaken, &i.IsUsernameTaken)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, username, password_hash, terms_accepted_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, username, status, is_active, is_admin, terms_accepted_at, activated_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID              uuid.UUID
	Email           string
	Username        string
	PasswordHash    string
	TermsAcceptedAt time.Time
}

type CreateUserRow struct {
	ID              uuid.UUID
	Email           string
	Username        string
	Status          string
	IsActive        bool
	IsAdmin         bool
	TermsAcceptedAt time.Time
	ActivatedAt     *time.Time
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.TermsAcceptedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Status,
		&i.IsActive,
		&i.IsAdmin,
		&i.TermsAcceptedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
