// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package usersstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users
SET is_active = true,
    activated_at = $1::timestamptz,
    status = CASE WHEN status = 'UNVERIFIED' THEN 'PENDING_PAYMENT' ELSE status END,
    updated_at = $1::timestamptz
WHERE id = $2 AND is_active = false
RETURNING id, email, username, status, is_active, is_admin, created_at, activated_at, last_login_at
`

type ActivateUserParams struct {
	ActivatedAt time.Time
	ID          uuid.UUID
}

type ActivateUserRow struct {
	ID          uuid.UUID
	Email       string
	Username    string
	Status      string
	IsActive    bool
	IsAdmin     bool
	CreatedAt   time.Time
	ActivatedAt *time.Time
	LastLoginAt *time.Time
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) (ActivateUserRow, error) {
	row := q.db.QueryRow(ctx, activateUser, arg.ActivatedAt, arg.ID)
	var i ActivateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Status,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const checkIdentifiersTaken = `-- name: CheckIdentifiersTaken :one
SELECT
    EXISTS (SELECT 1 FROM users WHERE lower(users.email) = lower($1::text)) AS is_email_taken,
    EXISTS (SELECT 1 FROM users WHERE lower(users.username) = lower($2::text)) AS is_username_taken
`

type CheckIdentifiersTakenParams struct {
	Email    string
	Username string
}

type CheckIdentifiersTakenRow struct {
	IsEmailTaken    bool
	IsUsernameTaken bool
}

func (q *Queries) CheckIdentifiersTaken(ctx context.Context, arg CheckIdentifiersTakenParams) (CheckIdentifiersTakenRow, error) {
	row := q.db.QueryRow(ctx, checkIdentifiersTaken, arg.Email, arg.Username)
	var i CheckIdentifiersTakenRow
	err := row.Scan(&i.IsEmailTaken, &i.IsUsernameTaken)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, username, password_hash, terms_accepted_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, username, status, is_active, is_admin, terms_accepted_at, activated_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID              uuid.UUID
	Email           string
	Username        string
	PasswordHash    string
	TermsAcceptedAt time.Time
}

type CreateUserRow struct {
	ID              uuid.UUID
	Email           string
	Username        string
	Status          string
	IsActive        bool
	IsAdmin         bool
	TermsAcceptedAt time.Time
	ActivatedAt     *time.Time
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.TermsAcceptedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Status,
		&i.IsActive,
		&i.IsAdmin,
		&i.TermsAcceptedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, username, status, is_active, is_admin, created_at, activated_at, last_login_at
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	ID          uuid.UUID
	Email       string
	Username    string
	Status      string
	IsActive    bool
	IsAdmin     bool
	CreatedAt   time.Time
	ActivatedAt *time.Time
	LastLoginAt *time.Time
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Status,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const findUserCredentialsByEmail = `-- name: FindUserCredentialsByEmail :one
SELECT id, email, username, password_hash, status, is_active, is_admin, created_at, last_login_at
FROM users
WHERE lower(email) = lower($1::text)
`

type FindUserCredentialsByEmailRow struct {
	ID           uuid.UUID
	Email        string
	Username     string
	PasswordHash string
	Status       string
	IsActive     bool
	IsAdmin      bool
	CreatedAt    time.Time
	LastLoginAt  *time.Time
}

func (q *Queries) FindUserCredentialsByEmail(ctx context.Context, email string) (FindUserCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserCredentialsByEmail, email)
	var i FindUserCredentialsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
		&i.IsActive,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const recordLogin = `-- name: RecordLogin :exec
UPDATE users
SET last_login_at = $2, updated_at = $2
WHERE id = $1
`

type RecordLoginParams struct {
	ID          uuid.UUID
	LastLoginAt *time.Time
}

func (q *Queries) RecordLogin(ctx context.Context, arg RecordLoginParams) error {
	_, err := q.db.Exec(ctx, recordLogin, arg.ID, arg.LastLoginAt)
	return err
}
