// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listItems = `-- name: ListItems :many
SELECT id, slug, name, category, tier, rarity_rank, is_tradeable, is_auction_only, max_supply, description, attributes
FROM items
ORDER BY id
`

type ListItemsRow struct {
	ID            int32
	Slug          string
	Name          string
	Category      string
	Tier          pgtype.Int4
	RarityRank    int32
	IsTradeable   bool
	IsAuctionOnly bool
	MaxSupply     pgtype.Int8
	Description   string
	Attributes    []byte
}

func (q *Queries) ListItems(ctx context.Context) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Category,
			&i.Tier,
			&i.RarityRank,
			&i.IsTradeable,
			&i.IsAuctionOnly,
			&i.MaxSupply,
			&i.Description,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLootTables = `-- name: ListLootTables :many
SELECT zone_id, item_id, minimum_quantity, maximum_quantity, chance_basis_points
FROM loot_tables
ORDER BY zone_id, item_id
`

func (q *Queries) ListLootTables(ctx context.Context) ([]LootTable, error) {
	rows, err := q.db.Query(ctx, listLootTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LootTable
	for rows.Next() {
		var i LootTable
		if err := rows.Scan(
			&i.ZoneID,
			&i.ItemID,
			&i.MinimumQuantity,
			&i.MaximumQuantity,
			&i.ChanceBasisPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeInputs = `-- name: ListRecipeInputs :many
SELECT recipe_id, item_id, quantity
FROM recipe_inputs
ORDER BY recipe_id, item_id
`

func (q *Queries) ListRecipeInputs(ctx context.Context) ([]RecipeInput, error) {
	rows, err := q.db.Query(ctx, listRecipeInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeInput
	for rows.Next() {
		var i RecipeInput
		if err := rows.Scan(&i.RecipeID, &i.ItemID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, output_item_id, output_quantity, craft_seconds, fee_micro
FROM recipes
WHERE is_enabled = true
ORDER BY output_item_id
`

type ListRecipesRow struct {
	ID             string
	OutputItemID   int32
	OutputQuantity int32
	CraftSeconds   int32
	FeeMicro       int64
}

func (q *Queries) ListRecipes(ctx context.Context) ([]ListRecipesRow, error) {
	rows, err := q.db.Query(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipesRow
	for rows.Next() {
		var i ListRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.OutputItemID,
			&i.OutputQuantity,
			&i.CraftSeconds,
			&i.FeeMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopSkuItems = `-- name: ListShopSkuItems :many
SELECT sku, item_id, quantity
FROM shop_sku_items
ORDER BY sku, item_id
`

func (q *Queries) ListShopSkuItems(ctx context.Context) ([]ShopSkuItem, error) {
	rows, err := q.db.Query(ctx, listShopSkuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopSkuItem
	for rows.Next() {
		var i ShopSkuItem
		if err := rows.Scan(&i.Sku, &i.ItemID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopSkus = `-- name: ListShopSkus :many
SELECT sku, name, description, price_micro
FROM shop_skus
WHERE is_enabled = true
ORDER BY sort_order
`

type ListShopSkusRow struct {
	Sku         string
	Name        string
	Description string
	PriceMicro  int64
}

func (q *Queries) ListShopSkus(ctx context.Context) ([]ListShopSkusRow, error) {
	rows, err := q.db.Query(ctx, listShopSkus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShopSkusRow
	for rows.Next() {
		var i ListShopSkusRow
		if err := rows.Scan(
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.PriceMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpgradeInputs = `-- name: ListUpgradeInputs :many
SELECT upgrade_id, item_id, quantity
FROM upgrade_inputs
ORDER BY upgrade_id, item_id
`

func (q *Queries) ListUpgradeInputs(ctx context.Context) ([]UpgradeInput, error) {
	rows, err := q.db.Query(ctx, listUpgradeInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpgradeInput
	for rows.Next() {
		var i UpgradeInput
		if err := rows.Scan(&i.UpgradeID, &i.ItemID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpgrades = `-- name: ListUpgrades :many
SELECT id, from_item_id, to_item_id, craft_fee_micro, buy_price_micro
FROM upgrades
WHERE is_enabled = true
ORDER BY from_item_id, to_item_id
`

type ListUpgradesRow struct {
	ID            string
	FromItemID    int32
	ToItemID      int32
	CraftFeeMicro int64
	BuyPriceMicro pgtype.Int8
}

func (q *Queries) ListUpgrades(ctx context.Context) ([]ListUpgradesRow, error) {
	rows, err := q.db.Query(ctx, listUpgrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpgradesRow
	for rows.Next() {
		var i ListUpgradesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromItemID,
			&i.ToItemID,
			&i.CraftFeeMicro,
			&i.BuyPriceMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZones = `-- name: ListZones :many
SELECT id, name, description, duration_seconds, fuel_cost, minimum_drill_tier, allowed_ship_item_ids
FROM zones
WHERE is_enabled = true
ORDER BY sort_order
`

type ListZonesRow struct {
	ID                 string
	Name               string
	Description        string
	DurationSeconds    int32
	FuelCost           int32
	MinimumDrillTier   int32
	AllowedShipItemIds []int32
}

func (q *Queries) ListZones(ctx context.Context) ([]ListZonesRow, error) {
	rows, err := q.db.Query(ctx, listZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListZonesRow
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DurationSeconds,
			&i.FuelCost,
			&i.MinimumDrillTier,
			&i.AllowedShipItemIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
