// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogstore

import (
	"context"
)

type Querier interface {
	ListItems(ctx context.Context) ([]ListItemsRow, error)
	ListLootTables(ctx context.Context) ([]LootTable, error)
	ListRecipeInputs(ctx context.Context) ([]RecipeInput, error)
	ListRecipes(ctx context.Context) ([]ListRecipesRow, error)
	ListShopSkuItems(ctx context.Context) ([]ShopSkuItem, error)
	ListShopSkus(ctx context.Context) ([]ListShopSkusRow, error)
	ListUpgradeInputs(ctx context.Context) ([]UpgradeInput, error)
	ListUpgrades(ctx context.Context) ([]ListUpgradesRow, error)
	ListZones(ctx context.Context) ([]ListZonesRow, error)
}

var _ Querier = (*Queries)(nil)
