// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package idempotencystore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeKey = `-- name: CompleteKey :exec
UPDATE idempotency_keys
SET status = 'completed',
    response_status_code = $3,
    response_content_type = $4,
    response_body = $5,
    completed_at = now()
WHERE scope = $1 AND idempotency_key = $2
`

type CompleteKeyParams struct {
	Scope               string
	IdempotencyKey      string
	ResponseStatusCode  pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
}

func (q *Queries) CompleteKey(ctx context.Context, arg CompleteKeyParams) error {
	_, err := q.db.Exec(ctx, completeKey,
		arg.Scope,
		arg.IdempotencyKey,
		arg.ResponseStatusCode,
		arg.ResponseContentType,
		arg.ResponseBody,
	)
	return err
}

const deleteKey = `-- name: DeleteKey :exec
DELETE FROM idempotency_keys
WHERE scope = $1 AND idempotency_key = $2
`

type DeleteKeyParams struct {
	Scope          string
	IdempotencyKey string
}

func (q *Queries) DeleteKey(ctx context.Context, arg DeleteKeyParams) error {
	_, err := q.db.Exec(ctx, deleteKey, arg.Scope, arg.IdempotencyKey)
	return err
}

const deleteKeyCreatedBefore = `-- name: DeleteKeyCreatedBefore :execrows
DELETE FROM idempotency_keys
WHERE scope = $1 AND idempotency_key = $2 AND created_at < $3
`

type DeleteKeyCreatedBeforeParams struct {
	Scope          string
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) DeleteKeyCreatedBefore(ctx context.Context, arg DeleteKeyCreatedBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKeyCreatedBefore, arg.Scope, arg.IdempotencyKey, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findKey = `-- name: FindKey :one
SELECT scope, idempotency_key, request_hash, status, response_status_code, response_content_type, response_body, created_at
FROM idempotency_keys
WHERE scope = $1 AND idempotency_key = $2
`

type FindKeyParams struct {
	Scope          string
	IdempotencyKey string
}

type FindKeyRow struct {
	Scope               string
	IdempotencyKey      string
	RequestHash         []byte
	Status              string
	ResponseStatusCode  pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) FindKey(ctx context.Context, arg FindKeyParams) (FindKeyRow, error) {
	row := q.db.QueryRow(ctx, findKey, arg.Scope, arg.IdempotencyKey)
	var i FindKeyRow
	err := row.Scan(
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatusCode,
		&i.ResponseContentType,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertInProgressKey = `-- name: InsertInProgressKey :execrows
INSERT INTO idempotency_keys (scope, idempotency_key, request_hash, status)
VALUES ($1, $2, $3, 'in_progress')
ON CONFLICT (scope, idempotency_key) DO NOTHING
`

type InsertInProgressKeyParams struct {
	Scope          string
	IdempotencyKey string
	RequestHash    []byte
}

func (q *Queries) InsertInProgressKey(ctx context.Context, arg InsertInProgressKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInProgressKey, arg.Scope, arg.IdempotencyKey, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
