// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package idempotencystore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountActivationToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type EmailOutbox struct {
	ID             pgtype.UUID
	Template       string
	RecipientEmail string
	RecipientName  string
	Subject        string
	HtmlBody       string
	TextBody       string
	Status         string
	Attempts       int32
	MaxAttempts    int32
	NextAttemptAt  pgtype.Timestamptz
	ClaimedUntil   pgtype.Timestamptz
	LastError      pgtype.Text
	SentAt         pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type IdempotencyKey struct {
	Scope               string
	IdempotencyKey      string
	RequestHash         []byte
	Status              string
	ResponseStatusCode  pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ReplacedBy pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID               pgtype.UUID
	Email            string
	Username         string
	PasswordHash     string
	Status           string
	IsActive         bool
	IsAdmin          bool
	TotpSecretEnc    []byte
	TermsAcceptedAt  pgtype.Timestamptz
	ActivatedAt      pgtype.Timestamptz
	LastLoginAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	TotpEnabledAt    pgtype.Timestamptz
	TotpLastUsedStep pgtype.Int8
}
