// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package idempotencystore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountActivationToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type EmailOutbox struct {
	ID             pgtype.UUID
	Template       string
	RecipientEmail string
	RecipientName  string
	Subject        string
	HtmlBody       string
	TextBody       string
	Status         string
	Attempts       int32
	MaxAttempts    int32
	NextAttemptAt  pgtype.Timestamptz
	ClaimedUntil   pgtype.Timestamptz
	LastError      pgtype.Text
	SentAt         pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ExternalEvent struct {
	ID          string
	Provider    string
	EventType   string
	Payload     []byte
	ReceivedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

type IdempotencyKey struct {
	Scope               string
	IdempotencyKey      string
	RequestHash         []byte
	Status              string
	ResponseStatusCode  pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

type Item struct {
	ID            int32
	Slug          string
	Name          string
	Category      string
	Tier          pgtype.Int4
	RarityRank    int32
	IsTradeable   bool
	IsAuctionOnly bool
	MaxSupply     pgtype.Int8
	Description   string
	Attributes    []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type LedgerAccount struct {
	ID            int64
	UserID        pgtype.UUID
	SystemAccount pgtype.Text
	ItemID        pgtype.Int4
	Bucket        pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type LedgerBalance struct {
	AccountID               int64
	Available               int64
	Held                    int64
	NegativeAvailablePolicy string
	UpdatedAt               pgtype.Timestamptz
}

type LedgerEntry struct {
	ID            int64
	JournalID     pgtype.UUID
	AccountID     int64
	Amount        int64
	SyncedOnchain bool
	CreatedAt     pgtype.Timestamptz
}

type LedgerHold struct {
	ID        pgtype.UUID
	AccountID int64
	Amount    int64
	Remaining int64
	RefType   string
	RefID     string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type LedgerJournal struct {
	ID        pgtype.UUID
	Type      string
	RefType   string
	RefID     string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type LootTable struct {
	ZoneID            string
	ItemID            int32
	MinimumQuantity   int32
	MaximumQuantity   int32
	ChanceBasisPoints int32
}

type Mission struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	ZoneID       string
	ShipItemID   int32
	DrillItemID  int32
	Status       string
	FuelSpent    int32
	ShipHoldID   pgtype.UUID
	DrillHoldID  pgtype.UUID
	ZoneSnapshot []byte
	Loot         []byte
	StartedAt    pgtype.Timestamptz
	EndsAt       pgtype.Timestamptz
	ResolvedAt   pgtype.Timestamptz
	CollectedAt  pgtype.Timestamptz
	AbortedAt    pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Payment struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Purpose            string
	Method             string
	Status             string
	AmountMicro        int64
	Sku                pgtype.Text
	CreditedMicro      pgtype.Int8
	PurposeStatus      string
	PurposeFailureCode pgtype.Text
	ProviderSessionID  pgtype.Text
	CheckoutUrl        pgtype.Text
	ExpiresAt          pgtype.Timestamptz
	SucceededAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Quantity           int32
}

type Recipe struct {
	ID             string
	OutputItemID   int32
	OutputQuantity int32
	CraftSeconds   int32
	FeeMicro       int64
	IsEnabled      bool
}

type RecipeInput struct {
	RecipeID string
	ItemID   int32
	Quantity int32
}

type RefreshToken struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	TokenHash        []byte
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	ReplacedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UserAgent        string
	IpAddress        string
	SessionStartedAt pgtype.Timestamptz
}

type ShopSku struct {
	Sku         string
	Name        string
	Description string
	PriceMicro  int64
	SortOrder   int32
	IsEnabled   bool
}

type ShopSkuItem struct {
	Sku      string
	ItemID   int32
	Quantity int32
}

type Upgrade struct {
	ID            string
	FromItemID    int32
	ToItemID      int32
	CraftFeeMicro int64
	BuyPriceMicro pgtype.Int8
	IsEnabled     bool
}

type UpgradeInput struct {
	UpgradeID string
	ItemID    int32
	Quantity  int32
}

type User struct {
	ID               pgtype.UUID
	Email            string
	Username         string
	PasswordHash     string
	Status           string
	IsActive         bool
	IsAdmin          bool
	TotpSecretEnc    []byte
	TermsAcceptedAt  pgtype.Timestamptz
	ActivatedAt      pgtype.Timestamptz
	LastLoginAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	TotpEnabledAt    pgtype.Timestamptz
	TotpLastUsedStep pgtype.Int8
}

type Zone struct {
	ID                 string
	Name               string
	Description        string
	DurationSeconds    int32
	FuelCost           int32
	MinimumDrillTier   int32
	AllowedShipItemIds []int32
	SortOrder          int32
	IsEnabled          bool
}
