// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package idempotencystore

import (
	"context"
)

type Querier interface {
	CompleteKey(ctx context.Context, arg CompleteKeyParams) error
	DeleteKey(ctx context.Context, arg DeleteKeyParams) error
	DeleteKeyCreatedBefore(ctx context.Context, arg DeleteKeyCreatedBeforeParams) (int64, error)
	FindKey(ctx context.Context, arg FindKeyParams) (FindKeyRow, error)
	InsertInProgressKey(ctx context.Context, arg InsertInProgressKeyParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
