// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_outbox.sql

package outboxstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimDueEmails = `-- name: ClaimDueEmails :many
UPDATE email_outbox
SET claimed_until = $1::timestamptz, updated_at = $2::timestamptz
WHERE id IN (
    SELECT candidate.id
    FROM email_outbox AS candidate
    WHERE candidate.status = 'pending'
      AND candidate.next_attempt_at <= $2::timestamptz
      AND (candidate.claimed_until IS NULL OR candidate.claimed_until < $2::timestamptz)
    ORDER BY candidate.next_attempt_at
    LIMIT $3::integer
)
  AND status = 'pending'
  AND (claimed_until IS NULL OR claimed_until < $2::timestamptz)
RETURNING id, template, recipient_email, recipient_name, subject, html_body, text_body, attempts, max_attempts
`

type ClaimDueEmailsParams struct {
	ClaimedUntil time.Time
	Now          time.Time
	BatchSize    int32
}

type ClaimDueEmailsRow struct {
	ID             uuid.UUID
	Template       string
	RecipientEmail string
	RecipientName  string
	Subject        string
	HtmlBody       string
	TextBody       string
	Attempts       int32
	MaxAttempts    int32
}

func (q *Queries) ClaimDueEmails(ctx context.Context, arg ClaimDueEmailsParams) ([]ClaimDueEmailsRow, error) {
	rows, err := q.db.Query(ctx, claimDueEmails, arg.ClaimedUntil, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueEmailsRow
	for rows.Next() {
		var i ClaimDueEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Template,
			&i.RecipientEmail,
			&i.RecipientName,
			&i.Subject,
			&i.HtmlBody,
			&i.TextBody,
			&i.Attempts,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueEmail = `-- name: EnqueueEmail :exec
INSERT INTO email_outbox (id, template, recipient_email, recipient_name, subject, html_body, text_body, max_attempts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type EnqueueEmailParams struct {
	ID             uuid.UUID
	Template       string
	RecipientEmail string
	RecipientName  string
	Subject        string
	HtmlBody       string
	TextBody       string
	MaxAttempts    int32
}

func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) error {
	_, err := q.db.Exec(ctx, enqueueEmail,
		arg.ID,
		arg.Template,
		arg.RecipientEmail,
		arg.RecipientName,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.MaxAttempts,
	)
	return err
}

const markEmailSent = `-- name: MarkEmailSent :exec
UPDATE email_outbox
SET status = 'sent', attempts = attempts + 1, sent_at = $1::timestamptz,
    claimed_until = NULL, last_error = NULL, updated_at = $1::timestamptz
WHERE id = $2
`

type MarkEmailSentParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkEmailSent(ctx context.Context, arg MarkEmailSentParams) error {
	_, err := q.db.Exec(ctx, markEmailSent, arg.Now, arg.ID)
	return err
}

const recordEmailFailure = `-- name: RecordEmailFailure :exec
UPDATE email_outbox
SET attempts = attempts + 1,
    status = CASE WHEN attempts + 1 >= max_attempts THEN 'failed' ELSE 'pending' END,
    next_attempt_at = $1::timestamptz,
    last_error = $2::text,
    claimed_until = NULL,
    updated_at = $3::timestamptz
WHERE id = $4
`

type RecordEmailFailureParams struct {
	NextAttemptAt time.Time
	LastError     string
	Now           time.Time
	ID            uuid.UUID
}

func (q *Queries) RecordEmailFailure(ctx context.Context, arg RecordEmailFailureParams) error {
	_, err := q.db.Exec(ctx, recordEmailFailure,
		arg.NextAttemptAt,
		arg.LastError,
		arg.Now,
		arg.ID,
	)
	return err
}
