// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package outboxstore

import (
	"context"
)

type Querier interface {
	ClaimDueEmails(ctx context.Context, arg ClaimDueEmailsParams) ([]ClaimDueEmailsRow, error)
	EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) error
	MarkEmailSent(ctx context.Context, arg MarkEmailSentParams) error
	RecordEmailFailure(ctx context.Context, arg RecordEmailFailureParams) error
}

var _ Querier = (*Queries)(nil)
