// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crafting.sql

package craftingstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deliverCraftJob = `-- name: DeliverCraftJob :one
UPDATE craft_jobs
SET status = 'DELIVERED', delivered_at = $1
WHERE id = $2 AND status = 'CRAFTING'
RETURNING id, user_id, recipe_id, quantity, output_item_id, output_quantity, fee_micro, inputs, status, started_at, ends_at, delivered_at
`

type DeliverCraftJobParams struct {
	DeliveredAt *time.Time
	ID          uuid.UUID
}

func (q *Queries) DeliverCraftJob(ctx context.Context, arg DeliverCraftJobParams) (CraftJob, error) {
	row := q.db.QueryRow(ctx, deliverCraftJob, arg.DeliveredAt, arg.ID)
	var i CraftJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipeID,
		&i.Quantity,
		&i.OutputItemID,
		&i.OutputQuantity,
		&i.FeeMicro,
		&i.Inputs,
		&i.Status,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeliveredAt,
	)
	return i, err
}

const insertCraftJob = `-- name: InsertCraftJob :one
INSERT INTO craft_jobs (id, user_id, recipe_id, quantity, output_item_id, output_quantity, fee_micro, inputs, started_at, ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id) WHERE status = 'CRAFTING' DO NOTHING
RETURNING id, user_id, recipe_id, quantity, output_item_id, output_quantity, fee_micro, inputs, status, started_at, ends_at, delivered_at
`

type InsertCraftJobParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	RecipeID       string
	Quantity       int32
	OutputItemID   int32
	OutputQuantity int32
	FeeMicro       int64
	Inputs         []byte
	StartedAt      time.Time
	EndsAt         time.Time
}

func (q *Queries) InsertCraftJob(ctx context.Context, arg InsertCraftJobParams) (CraftJob, error) {
	row := q.db.QueryRow(ctx, insertCraftJob,
		arg.ID,
		arg.UserID,
		arg.RecipeID,
		arg.Quantity,
		arg.OutputItemID,
		arg.OutputQuantity,
		arg.FeeMicro,
		arg.Inputs,
		arg.StartedAt,
		arg.EndsAt,
	)
	var i CraftJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipeID,
		&i.Quantity,
		&i.OutputItemID,
		&i.OutputQuantity,
		&i.FeeMicro,
		&i.Inputs,
		&i.Status,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listCraftJobsForUser = `-- name: ListCraftJobsForUser :many
SELECT id, user_id, recipe_id, quantity, output_item_id, output_quantity, fee_micro, inputs, status, started_at, ends_at, delivered_at FROM craft_jobs
WHERE user_id = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY id DESC
LIMIT $4
`

type ListCraftJobsForUserParams struct {
	UserID   uuid.UUID
	BeforeID *uuid.UUID
	Status   *string
	RowLimit int32
}

func (q *Queries) ListCraftJobsForUser(ctx context.Context, arg ListCraftJobsForUserParams) ([]CraftJob, error) {
	rows, err := q.db.Query(ctx, listCraftJobsForUser,
		arg.UserID,
		arg.BeforeID,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CraftJob
	for rows.Next() {
		var i CraftJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecipeID,
			&i.Quantity,
			&i.OutputItemID,
			&i.OutputQuantity,
			&i.FeeMicro,
			&i.Inputs,
			&i.Status,
			&i.StartedAt,
			&i.EndsAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCraftJobs = `-- name: ListDueCraftJobs :many
SELECT id, user_id, recipe_id, quantity, output_item_id, output_quantity, fee_micro, inputs, status, started_at, ends_at, delivered_at FROM craft_jobs
WHERE status = 'CRAFTING' AND ends_at <= $1
ORDER BY ends_at
LIMIT $2
`

type ListDueCraftJobsParams struct {
	Now      time.Time
	RowLimit int32
}

func (q *Queries) ListDueCraftJobs(ctx context.Context, arg ListDueCraftJobsParams) ([]CraftJob, error) {
	rows, err := q.db.Query(ctx, listDueCraftJobs, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CraftJob
	for rows.Next() {
		var i CraftJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecipeID,
			&i.Quantity,
			&i.OutputItemID,
			&i.OutputQuantity,
			&i.FeeMicro,
			&i.Inputs,
			&i.Status,
			&i.StartedAt,
			&i.EndsAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
