// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package craftingstore

import (
	"context"
)

type Querier interface {
	DeliverCraftJob(ctx context.Context, arg DeliverCraftJobParams) (CraftJob, error)
	InsertCraftJob(ctx context.Context, arg InsertCraftJobParams) (CraftJob, error)
	ListCraftJobsForUser(ctx context.Context, arg ListCraftJobsForUserParams) ([]CraftJob, error)
	ListDueCraftJobs(ctx context.Context, arg ListDueCraftJobsParams) ([]CraftJob, error)
}

var _ Querier = (*Queries)(nil)
