// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package ledgerstore

import (
	"context"
)

// iteratorForInsertEntries implements pgx.CopyFromSource.
type iteratorForInsertEntries struct {
	rows                 []InsertEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].JournalID,
		r.rows[0].AccountID,
		r.rows[0].Amount,
	}, nil
}

func (r iteratorForInsertEntries) Err() error {
	return nil
}

func (q *Queries) InsertEntries(ctx context.Context, arg []InsertEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ledger_entries"}, []string{"journal_id", "account_id", "amount"}, &iteratorForInsertEntries{rows: arg})
}
