// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package ledgerstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyAvailableChange = `-- name: ApplyAvailableChange :one
UPDATE ledger_balances
SET available = available + $1, updated_at = now()
WHERE account_id = $2
  AND (
      available + $1 >= 0
      OR negative_available_policy = 'always'
      OR (negative_available_policy = 'dispute_only' AND $3::boolean)
  )
RETURNING available
`

type ApplyAvailableChangeParams struct {
	Change                 int64
	AccountID              int64
	AllowsDisputeOverdraft bool
}

func (q *Queries) ApplyAvailableChange(ctx context.Context, arg ApplyAvailableChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, applyAvailableChange, arg.Change, arg.AccountID, arg.AllowsDisputeOverdraft)
	var available int64
	err := row.Scan(&available)
	return available, err
}

const findAccount = `-- name: FindAccount :one
SELECT id
FROM ledger_accounts
WHERE user_id IS NOT DISTINCT FROM $1::uuid
  AND system_account IS NOT DISTINCT FROM $2::text
  AND item_id IS NOT DISTINCT FROM $3::integer
  AND bucket IS NOT DISTINCT FROM $4::text
`

type FindAccountParams struct {
	UserID        *uuid.UUID
	SystemAccount *string
	ItemID        *int32
	Bucket        *string
}

func (q *Queries) FindAccount(ctx context.Context, arg FindAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, findAccount,
		arg.UserID,
		arg.SystemAccount,
		arg.ItemID,
		arg.Bucket,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findBalancesNotMatchingEntries = `-- name: FindBalancesNotMatchingEntries :many
SELECT b.account_id, (b.available + b.held)::bigint AS balance_total, COALESCE(entry_totals.total, 0)::bigint AS entries_total
FROM ledger_balances b
LEFT JOIN (
    SELECT account_id, SUM(amount) AS total FROM ledger_entries GROUP BY account_id
) entry_totals ON entry_totals.account_id = b.account_id
WHERE b.available + b.held <> COALESCE(entry_totals.total, 0)
LIMIT 50
`

type FindBalancesNotMatchingEntriesRow struct {
	AccountID    int64
	BalanceTotal int64
	EntriesTotal int64
}

func (q *Queries) FindBalancesNotMatchingEntries(ctx context.Context) ([]FindBalancesNotMatchingEntriesRow, error) {
	rows, err := q.db.Query(ctx, findBalancesNotMatchingEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindBalancesNotMatchingEntriesRow
	for rows.Next() {
		var i FindBalancesNotMatchingEntriesRow
		if err := rows.Scan(&i.AccountID, &i.BalanceTotal, &i.EntriesTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findHeldNotMatchingHolds = `-- name: FindHeldNotMatchingHolds :many
SELECT b.account_id, b.held, COALESCE(hold_totals.total, 0)::bigint AS active_holds_total
FROM ledger_balances b
LEFT JOIN (
    SELECT account_id, SUM(remaining) AS total FROM ledger_holds WHERE status = 'ACTIVE' GROUP BY account_id
) hold_totals ON hold_totals.account_id = b.account_id
WHERE b.held <> COALESCE(hold_totals.total, 0)
LIMIT 50
`

type FindHeldNotMatchingHoldsRow struct {
	AccountID        int64
	Held             int64
	ActiveHoldsTotal int64
}

func (q *Queries) FindHeldNotMatchingHolds(ctx context.Context) ([]FindHeldNotMatchingHoldsRow, error) {
	rows, err := q.db.Query(ctx, findHeldNotMatchingHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindHeldNotMatchingHoldsRow
	for rows.Next() {
		var i FindHeldNotMatchingHoldsRow
		if err := rows.Scan(&i.AccountID, &i.Held, &i.ActiveHoldsTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUnbalancedJournals = `-- name: FindUnbalancedJournals :many
SELECT e.journal_id, COALESCE(a.item_id, 0)::integer AS asset_item_id, SUM(e.amount)::bigint AS total
FROM ledger_entries e
JOIN ledger_accounts a ON a.id = e.account_id
GROUP BY e.journal_id, COALESCE(a.item_id, 0)
HAVING SUM(e.amount) <> 0
LIMIT 50
`

type FindUnbalancedJournalsRow struct {
	JournalID   uuid.UUID
	AssetItemID int32
	Total       int64
}

func (q *Queries) FindUnbalancedJournals(ctx context.Context) ([]FindUnbalancedJournalsRow, error) {
	rows, err := q.db.Query(ctx, findUnbalancedJournals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUnbalancedJournalsRow
	for rows.Next() {
		var i FindUnbalancedJournalsRow
		if err := rows.Scan(&i.JournalID, &i.AssetItemID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalance = `-- name: GetBalance :one
SELECT available, held
FROM ledger_balances
WHERE account_id = $1
`

type GetBalanceRow struct {
	Available int64
	Held      int64
}

func (q *Queries) GetBalance(ctx context.Context, accountID int64) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var i GetBalanceRow
	err := row.Scan(&i.Available, &i.Held)
	return i, err
}

const getHold = `-- name: GetHold :one
SELECT id, account_id, amount, remaining, ref_type, ref_id, status
FROM ledger_holds
WHERE id = $1
`

type GetHoldRow struct {
	ID        uuid.UUID
	AccountID int64
	Amount    int64
	Remaining int64
	RefType   string
	RefID     string
	Status    string
}

func (q *Queries) GetHold(ctx context.Context, id uuid.UUID) (GetHoldRow, error) {
	row := q.db.QueryRow(ctx, getHold, id)
	var i GetHoldRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Remaining,
		&i.RefType,
		&i.RefID,
		&i.Status,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
WITH inserted_account AS (
    INSERT INTO ledger_accounts (user_id, system_account, item_id, bucket)
    VALUES ($1::uuid, $2::text, $3::integer, $4::text)
    ON CONFLICT ON CONSTRAINT ledger_accounts_owner_asset_bucket_key DO NOTHING
    RETURNING id
), inserted_balance AS (
    INSERT INTO ledger_balances (account_id, negative_available_policy)
    SELECT id, $5::text FROM inserted_account
)
SELECT id FROM inserted_account
`

type InsertAccountParams struct {
	UserID                  *uuid.UUID
	SystemAccount           *string
	ItemID                  *int32
	Bucket                  *string
	NegativeAvailablePolicy string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.UserID,
		arg.SystemAccount,
		arg.ItemID,
		arg.Bucket,
		arg.NegativeAvailablePolicy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

type InsertEntriesParams struct {
	JournalID uuid.UUID
	AccountID int64
	Amount    int64
}

const insertHold = `-- name: InsertHold :one
INSERT INTO ledger_holds (id, account_id, amount, remaining, ref_type, ref_id)
VALUES ($1, $2, $3, $3, $4, $5)
ON CONFLICT ON CONSTRAINT ledger_holds_reference_key DO NOTHING
RETURNING id
`

type InsertHoldParams struct {
	ID        uuid.UUID
	AccountID int64
	Amount    int64
	RefType   string
	RefID     string
}

func (q *Queries) InsertHold(ctx context.Context, arg InsertHoldParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertHold,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.RefType,
		arg.RefID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertJournal = `-- name: InsertJournal :one
INSERT INTO ledger_journals (id, type, ref_type, ref_id, metadata)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ON CONSTRAINT ledger_journals_business_event_key DO NOTHING
RETURNING id
`

type InsertJournalParams struct {
	ID       uuid.UUID
	Type     string
	RefType  string
	RefID    string
	Metadata []byte
}

func (q *Queries) InsertJournal(ctx context.Context, arg InsertJournalParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertJournal,
		arg.ID,
		arg.Type,
		arg.RefType,
		arg.RefID,
		arg.Metadata,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAccountsByID = `-- name: ListAccountsByID :many
SELECT a.id, a.user_id, a.system_account, a.item_id, a.bucket, b.negative_available_policy
FROM ledger_accounts a
JOIN ledger_balances b ON b.account_id = a.id
WHERE a.id = ANY($1::bigint[])
`

type ListAccountsByIDRow struct {
	ID                      int64
	UserID                  *uuid.UUID
	SystemAccount           *string
	ItemID                  *int32
	Bucket                  *string
	NegativeAvailablePolicy string
}

func (q *Queries) ListAccountsByID(ctx context.Context, accountIds []int64) ([]ListAccountsByIDRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByID, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByIDRow
	for rows.Next() {
		var i ListAccountsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SystemAccount,
			&i.ItemID,
			&i.Bucket,
			&i.NegativeAvailablePolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerInventory = `-- name: ListPlayerInventory :many
SELECT a.item_id::integer AS item_id, b.available, b.held
FROM ledger_accounts a
JOIN ledger_balances b ON b.account_id = a.id
WHERE a.user_id = $1
  AND a.item_id IS NOT NULL
  AND (b.available <> 0 OR b.held <> 0)
  AND a.item_id > $2::integer
ORDER BY a.item_id
LIMIT $3
`

type ListPlayerInventoryParams struct {
	UserID      *uuid.UUID
	AfterItemID int32
	RowLimit    int32
}

type ListPlayerInventoryRow struct {
	ItemID    int32
	Available int64
	Held      int64
}

func (q *Queries) ListPlayerInventory(ctx context.Context, arg ListPlayerInventoryParams) ([]ListPlayerInventoryRow, error) {
	rows, err := q.db.Query(ctx, listPlayerInventory, arg.UserID, arg.AfterItemID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerInventoryRow
	for rows.Next() {
		var i ListPlayerInventoryRow
		if err := rows.Scan(&i.ItemID, &i.Available, &i.Held); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerJournalEntries = `-- name: ListPlayerJournalEntries :many
SELECT e.journal_id, a.item_id, a.bucket, SUM(e.amount)::bigint AS amount
FROM ledger_entries e
JOIN ledger_accounts a ON a.id = e.account_id
WHERE e.journal_id = ANY($1::uuid[]) AND a.user_id = $2
GROUP BY e.journal_id, a.item_id, a.bucket
HAVING SUM(e.amount) <> 0
ORDER BY e.journal_id, a.item_id NULLS FIRST, a.bucket
`

type ListPlayerJournalEntriesParams struct {
	JournalIds []uuid.UUID
	UserID     *uuid.UUID
}

type ListPlayerJournalEntriesRow struct {
	JournalID uuid.UUID
	ItemID    *int32
	Bucket    *string
	Amount    int64
}

func (q *Queries) ListPlayerJournalEntries(ctx context.Context, arg ListPlayerJournalEntriesParams) ([]ListPlayerJournalEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPlayerJournalEntries, arg.JournalIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerJournalEntriesRow
	for rows.Next() {
		var i ListPlayerJournalEntriesRow
		if err := rows.Scan(
			&i.JournalID,
			&i.ItemID,
			&i.Bucket,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerJournalTypesAmong = `-- name: ListPlayerJournalTypesAmong :many
SELECT DISTINCT j.type
FROM ledger_accounts a
JOIN ledger_entries e ON e.account_id = a.id
JOIN ledger_journals j ON j.id = e.journal_id
WHERE a.user_id = $1 AND j.type = ANY($2::text[])
`

type ListPlayerJournalTypesAmongParams struct {
	UserID       *uuid.UUID
	JournalTypes []string
}

func (q *Queries) ListPlayerJournalTypesAmong(ctx context.Context, arg ListPlayerJournalTypesAmongParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlayerJournalTypesAmong, arg.UserID, arg.JournalTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerJournals = `-- name: ListPlayerJournals :many
SELECT DISTINCT j.id, j.type, j.ref_type, j.ref_id, j.created_at
FROM ledger_accounts a
JOIN ledger_entries e ON e.account_id = a.id
JOIN ledger_journals j ON j.id = e.journal_id
WHERE a.user_id = $1
  AND ($2::uuid IS NULL OR j.id < $2::uuid)
  AND ($3::text IS NULL OR j.type = $3::text)
ORDER BY j.id DESC
LIMIT $4
`

type ListPlayerJournalsParams struct {
	UserID          *uuid.UUID
	BeforeJournalID *uuid.UUID
	JournalType     *string
	RowLimit        int32
}

type ListPlayerJournalsRow struct {
	ID        uuid.UUID
	Type      string
	RefType   string
	RefID     string
	CreatedAt time.Time
}

func (q *Queries) ListPlayerJournals(ctx context.Context, arg ListPlayerJournalsParams) ([]ListPlayerJournalsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerJournals,
		arg.UserID,
		arg.BeforeJournalID,
		arg.JournalType,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerJournalsRow
	for rows.Next() {
		var i ListPlayerJournalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.RefType,
			&i.RefID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerNCBalances = `-- name: ListPlayerNCBalances :many
SELECT a.id, a.bucket, b.available, b.held
FROM ledger_accounts a
JOIN ledger_balances b ON b.account_id = a.id
WHERE a.user_id = $1 AND a.item_id IS NULL
`

type ListPlayerNCBalancesRow struct {
	ID        int64
	Bucket    *string
	Available int64
	Held      int64
}

func (q *Queries) ListPlayerNCBalances(ctx context.Context, userID *uuid.UUID) ([]ListPlayerNCBalancesRow, error) {
	rows, err := q.db.Query(ctx, listPlayerNCBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerNCBalancesRow
	for rows.Next() {
		var i ListPlayerNCBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Bucket,
			&i.Available,
			&i.Held,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAvailableToHeld = `-- name: MoveAvailableToHeld :one
UPDATE ledger_balances
SET available = available - $1, held = held + $1, updated_at = now()
WHERE account_id = $2 AND available >= $1
RETURNING available
`

type MoveAvailableToHeldParams struct {
	Amount    int64
	AccountID int64
}

func (q *Queries) MoveAvailableToHeld(ctx context.Context, arg MoveAvailableToHeldParams) (int64, error) {
	row := q.db.QueryRow(ctx, moveAvailableToHeld, arg.Amount, arg.AccountID)
	var available int64
	err := row.Scan(&available)
	return available, err
}

const moveHeldToAvailable = `-- name: MoveHeldToAvailable :one
UPDATE ledger_balances
SET available = available + $1, held = held - $1, updated_at = now()
WHERE account_id = $2 AND held >= $1
RETURNING held
`

type MoveHeldToAvailableParams struct {
	Amount    int64
	AccountID int64
}

func (q *Queries) MoveHeldToAvailable(ctx context.Context, arg MoveHeldToAvailableParams) (int64, error) {
	row := q.db.QueryRow(ctx, moveHeldToAvailable, arg.Amount, arg.AccountID)
	var held int64
	err := row.Scan(&held)
	return held, err
}

const reduceHold = `-- name: ReduceHold :one
UPDATE ledger_holds
SET remaining = remaining - $1,
    status = CASE WHEN remaining - $1 = 0 THEN $2::text ELSE status END,
    updated_at = now()
WHERE id = $3 AND status = 'ACTIVE' AND remaining >= $1
RETURNING account_id, remaining
`

type ReduceHoldParams struct {
	Amount      int64
	FinalStatus string
	ID          uuid.UUID
}

type ReduceHoldRow struct {
	AccountID int64
	Remaining int64
}

func (q *Queries) ReduceHold(ctx context.Context, arg ReduceHoldParams) (ReduceHoldRow, error) {
	row := q.db.QueryRow(ctx, reduceHold, arg.Amount, arg.FinalStatus, arg.ID)
	var i ReduceHoldRow
	err := row.Scan(&i.AccountID, &i.Remaining)
	return i, err
}

const takeFromHeld = `-- name: TakeFromHeld :one
UPDATE ledger_balances
SET held = held - $1, updated_at = now()
WHERE account_id = $2 AND held >= $1
RETURNING held
`

type TakeFromHeldParams struct {
	Amount    int64
	AccountID int64
}

func (q *Queries) TakeFromHeld(ctx context.Context, arg TakeFromHeldParams) (int64, error) {
	row := q.db.QueryRow(ctx, takeFromHeld, arg.Amount, arg.AccountID)
	var held int64
	err := row.Scan(&held)
	return held, err
}
