// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ledgerstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ApplyAvailableChange(ctx context.Context, arg ApplyAvailableChangeParams) (int64, error)
	FindAccount(ctx context.Context, arg FindAccountParams) (int64, error)
	FindBalancesNotMatchingEntries(ctx context.Context) ([]FindBalancesNotMatchingEntriesRow, error)
	FindHeldNotMatchingHolds(ctx context.Context) ([]FindHeldNotMatchingHoldsRow, error)
	FindUnbalancedJournals(ctx context.Context) ([]FindUnbalancedJournalsRow, error)
	GetBalance(ctx context.Context, accountID int64) (GetBalanceRow, error)
	GetHold(ctx context.Context, id uuid.UUID) (GetHoldRow, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (int64, error)
	InsertEntries(ctx context.Context, arg []InsertEntriesParams) (int64, error)
	InsertHold(ctx context.Context, arg InsertHoldParams) (uuid.UUID, error)
	InsertJournal(ctx context.Context, arg InsertJournalParams) (uuid.UUID, error)
	ListAccountsByID(ctx context.Context, accountIds []int64) ([]ListAccountsByIDRow, error)
	ListPlayerNCBalances(ctx context.Context, userID *uuid.UUID) ([]ListPlayerNCBalancesRow, error)
	MoveAvailableToHeld(ctx context.Context, arg MoveAvailableToHeldParams) (int64, error)
	MoveHeldToAvailable(ctx context.Context, arg MoveHeldToAvailableParams) (int64, error)
	ReduceHold(ctx context.Context, arg ReduceHoldParams) (ReduceHoldRow, error)
	TakeFromHeld(ctx context.Context, arg TakeFromHeldParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
