// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package inappstore

import (
	"time"

	"github.com/google/uuid"
)

type AccountActivationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type CraftJob struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	RecipeID       string
	Quantity       int32
	OutputItemID   int32
	OutputQuantity int32
	FeeMicro       int64
	Inputs         []byte
	Status         string
	StartedAt      time.Time
	EndsAt         time.Time
	DeliveredAt    *time.Time
}

type EmailOutbox struct {
	ID             uuid.UUID
	Template       string
	RecipientEmail string
	RecipientName  string
	Subject        string
	HtmlBody       string
	TextBody       string
	Status         string
	Attempts       int32
	MaxAttempts    int32
	NextAttemptAt  time.Time
	ClaimedUntil   *time.Time
	LastError      *string
	SentAt         *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ExternalEvent struct {
	ID          string
	Provider    string
	EventType   string
	Payload     []byte
	ReceivedAt  time.Time
	ProcessedAt *time.Time
}

type IdempotencyKey struct {
	Scope               string
	IdempotencyKey      string
	RequestHash         []byte
	Status              string
	ResponseStatusCode  *int32
	ResponseContentType *string
	ResponseBody        []byte
	CreatedAt           time.Time
	CompletedAt         *time.Time
}

type Item struct {
	ID            int32
	Slug          string
	Name          string
	Category      string
	Tier          *int32
	RarityRank    int32
	IsTradeable   bool
	IsAuctionOnly bool
	MaxSupply     *int64
	Description   string
	Attributes    []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type LedgerAccount struct {
	ID            int64
	UserID        *uuid.UUID
	SystemAccount *string
	ItemID        *int32
	Bucket        *string
	CreatedAt     time.Time
}

type LedgerBalance struct {
	AccountID               int64
	Available               int64
	Held                    int64
	NegativeAvailablePolicy string
	UpdatedAt               time.Time
}

type LedgerEntry struct {
	ID            int64
	JournalID     uuid.UUID
	AccountID     int64
	Amount        int64
	SyncedOnchain bool
	CreatedAt     time.Time
}

type LedgerHold struct {
	ID        uuid.UUID
	AccountID int64
	Amount    int64
	Remaining int64
	RefType   string
	RefID     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LedgerJournal struct {
	ID        uuid.UUID
	Type      string
	RefType   string
	RefID     string
	Metadata  []byte
	CreatedAt time.Time
}

type LootTable struct {
	ZoneID            string
	ItemID            int32
	MinimumQuantity   int32
	MaximumQuantity   int32
	ChanceBasisPoints int32
}

type Mission struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ZoneID       string
	ShipItemID   int32
	DrillItemID  int32
	Status       string
	FuelSpent    int32
	ShipHoldID   uuid.UUID
	DrillHoldID  uuid.UUID
	ZoneSnapshot []byte
	Loot         []byte
	StartedAt    time.Time
	EndsAt       time.Time
	ResolvedAt   *time.Time
	CollectedAt  *time.Time
	AbortedAt    *time.Time
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	Title     string
	Body      string
	Link      string
	CreatedAt time.Time
	ReadAt    *time.Time
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Payment struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Purpose            string
	Method             string
	Status             string
	AmountMicro        int64
	Sku                *string
	CreditedMicro      *int64
	PurposeStatus      string
	PurposeFailureCode *string
	ProviderSessionID  *string
	CheckoutUrl        *string
	ExpiresAt          time.Time
	SucceededAt        *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Quantity           int32
	UpgradeID          *string
}

type Recipe struct {
	ID             string
	OutputItemID   int32
	OutputQuantity int32
	CraftSeconds   int32
	FeeMicro       int64
	IsEnabled      bool
}

type RecipeInput struct {
	RecipeID string
	ItemID   int32
	Quantity int32
}

type RefreshToken struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	TokenHash        []byte
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	ReplacedBy       *uuid.UUID
	CreatedAt        time.Time
	UserAgent        string
	IpAddress        string
	SessionStartedAt time.Time
}

type ShopSku struct {
	Sku         string
	Name        string
	Description string
	PriceMicro  int64
	SortOrder   int32
	IsEnabled   bool
}

type ShopSkuItem struct {
	Sku      string
	ItemID   int32
	Quantity int32
}

type Upgrade struct {
	ID            string
	FromItemID    int32
	ToItemID      int32
	CraftFeeMicro int64
	BuyPriceMicro *int64
	IsEnabled     bool
}

type UpgradeInput struct {
	UpgradeID string
	ItemID    int32
	Quantity  int32
}

type User struct {
	ID               uuid.UUID
	Email            string
	Username         string
	PasswordHash     string
	Status           string
	IsActive         bool
	IsAdmin          bool
	TotpSecretEnc    []byte
	TermsAcceptedAt  time.Time
	ActivatedAt      *time.Time
	LastLoginAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	TotpEnabledAt    *time.Time
	TotpLastUsedStep *int64
}

type Zone struct {
	ID                 string
	Name               string
	Description        string
	DurationSeconds    int32
	FuelCost           int32
	MinimumDrillTier   int32
	AllowedShipItemIds []int32
	SortOrder          int32
	IsEnabled          bool
}
