// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package inappstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::integer FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (id, user_id, kind, title, body, link)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, kind, title, body, link, created_at, read_at
`

type InsertNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Kind   string
	Title  string
	Body   string
	Link   string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, kind, title, body, link, created_at, read_at FROM notifications
WHERE user_id = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
  AND (NOT $3::boolean OR read_at IS NULL)
ORDER BY id DESC
LIMIT $4
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	BeforeID   *uuid.UUID
	UnreadOnly bool
	RowLimit   int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.BeforeID,
		arg.UnreadOnly,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :one
WITH marked AS (
    UPDATE notifications
    SET read_at = $1
    WHERE user_id = $2
      AND read_at IS NULL
      AND ($3::boolean OR id = ANY($4::uuid[]))
    RETURNING id
)
SELECT count(*)::integer FROM marked
`

type MarkNotificationsReadParams struct {
	ReadAt          *time.Time
	UserID          uuid.UUID
	MarkAll         bool
	NotificationIds []uuid.UUID
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) (int32, error) {
	row := q.db.QueryRow(ctx, markNotificationsRead,
		arg.ReadAt,
		arg.UserID,
		arg.MarkAll,
		arg.NotificationIds,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
