// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package inappstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int32, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
